// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmwyvk8rN4FPde22ChyupiGydGFFaBMzc',
    appId: '1:630152691138:web:cd849e1950511980a1aa5b',
    messagingSenderId: '630152691138',
    projectId: 'ecommerceapp-18c7c',
    authDomain: 'ecommerceapp-18c7c.firebaseapp.com',
    storageBucket: 'ecommerceapp-18c7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkAl3EFDxTc_mTUesy2Z4OL6SSrF_StPQ',
    appId: '1:630152691138:android:da4c245198ddc0d3a1aa5b',
    messagingSenderId: '630152691138',
    projectId: 'ecommerceapp-18c7c',
    storageBucket: 'ecommerceapp-18c7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxO83ACgtF79dwGgm3t0KQz5iiPKQuU1M',
    appId: '1:630152691138:ios:30d70d50db0d2392a1aa5b',
    messagingSenderId: '630152691138',
    projectId: 'ecommerceapp-18c7c',
    storageBucket: 'ecommerceapp-18c7c.appspot.com',
    androidClientId: '630152691138-r21klco67729h9ni96dr4hmj0qcd38se.apps.googleusercontent.com',
    iosClientId: '630152691138-sbf0guuedn4ui5832l1sk8v2tm6oc622.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxO83ACgtF79dwGgm3t0KQz5iiPKQuU1M',
    appId: '1:630152691138:ios:30d70d50db0d2392a1aa5b',
    messagingSenderId: '630152691138',
    projectId: 'ecommerceapp-18c7c',
    storageBucket: 'ecommerceapp-18c7c.appspot.com',
    androidClientId: '630152691138-r21klco67729h9ni96dr4hmj0qcd38se.apps.googleusercontent.com',
    iosClientId: '630152691138-sbf0guuedn4ui5832l1sk8v2tm6oc622.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmwyvk8rN4FPde22ChyupiGydGFFaBMzc',
    appId: '1:630152691138:web:4fc2e6533db9e2bca1aa5b',
    messagingSenderId: '630152691138',
    projectId: 'ecommerceapp-18c7c',
    authDomain: 'ecommerceapp-18c7c.firebaseapp.com',
    storageBucket: 'ecommerceapp-18c7c.appspot.com',
  );

}